### ISSUE TITLE
Output files overwritten

### ISSUE THREAD

**Issue by nathankota** [agrc/DEQ-TankRisk#18]
Output folder contents are overwritten each time the tool is run. Successive tool runs should keep previous outputs and add new results.

**Comment by steveoh** [comment]
the current work around for this is to choose a separate folder for the output

**Comment by steveoh** [comment]
I'm not sure how this is happening because 
https://github.com/agrc/DEQ-TankRisk/blob/03d1e6b3cbfa2b8d602c65fab1ab4658867692d0/src/tank_risk.py#L90-L94
generates unique folder names based on a time string which is unique every second.

I also cannot reproduce. Is this something the client is experiencing? 

![image](https://user-images.githubusercontent.com/325813/70754976-da1b2a00-1cf5-11ea-88c8-a38083f9029a.png)

**Comment by nathankota** [comment]
Yes, client is experiencing. Further client testing of this has been requested, using a different output location.

**Comment by steveoh** [comment]
It appears that pro deletes the contents of the folder on each run. What do you suggest we do here?

**Comment by nathankota** [comment]
Maybe it becomes part of their workflow to transfer and save output files to a different directory. I'll discuss with DEQ.
